# Включённые директории
included:
  - FakeNFT

# Исключённые пути
excluded:
  - Pods
  - DerivedData
  - .build
  - Tests

# Отключённые правила
disabled_rules:
  - trailing_whitespace
  - todo
  - multiple_closures_with_trailing_closure

# Необязательные, но полезные правила
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - force_unwrapping
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call

# Настройка уровней серьезности
force_cast: error
force_try: warning
force_unwrapping: error

# Конфигурация параметров правил
line_length:
  warning: 100
  error: 140
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

# Формат вывода
reporter: "xcode"