name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install dependencies
        run: |
          brew install xcodegen
          brew install swiftlint
          brew install swiftformat

      - name: Create Secrets.xcconfig
        run: |
          cp FakeNFT/Secrets.xcconfig.example FakeNFT/Secrets.xcconfig
          echo "API_KEY = ${{ secrets.API_KEY }}" > FakeNFT/Secrets.xcconfig
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Run SwiftFormat
        run: swiftformat .

      - name: Run SwiftLint
        run: swiftlint

      - name: Build FakeNFT scheme
        run: |
          set -o pipefail && xcodebuild clean build \
            -scheme FakeNFT \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty